### ISSUE TITLE
quickjs-2019-07-28 has been released

### ISSUE THREAD

**Issue by mlvzk** [theduke/quickjs-rs#1]
any chance you could update the crate to use the 2019-07-28 version?

PS: Thanks for these great bindings!

**Comment by theduke** [comment]
Yup, I'll get to it tomorrow.

**Comment by theduke** [comment]
@mlvzk I will publish a new version once I have #4 and #5  done.

PS: if you are ever in the situation again that you are blocked on a new QuickJS version, you can:
* Clone the repo
* Update the download URL in `./justfile`
* Install https://github.com/casey/just
* run `just quickjs-update`

This will update the embedded bindings.
