### ISSUE TITLE
Questions about design/architecture

### ISSUE THREAD

**Issue by andrieshiemstra** [theduke/quickjs-rs#101]
Hi theduke,

So i thought i'd share some of my advancements on functionality as discussed in #78, #53, #40, #24

The first four are a bit more complicated than i anticipated because i rely quite a bit on my JSValueRef which automatically calls DupValue and FreeValue on clone/drop (see https://github.com/HiRoFa/quickjs_es_runtime/blob/master/src/valueref.rs)

So my first question is: Would it be ok to alter your OwnedValueRef in the same way?

Second, since you made a optional feature out of bigint would i be correctly assuming you would also want optional features for bytecodecompilation/modules/reflection etc to keep binaries as compact as possible?

i thould i'd make a "utils" mod with some mods nested there
* compile.rs for #53
* fetch.rs for #24 
* modules.rs for #40
* reflection.rs (create proxies and such) for #78

Kind regards

**Comment by theduke** [comment]
> since you made a optional feature out of bigint

Bigint is optional because it requires an extra dependency.

The things you mention shouldn't need any dependencies, so no need to put them behind features.

> Would it be ok to alter your OwnedValueRef in the same way?

`OwnedValueRef` already has a `Drop` impl that frees the JSValue. 
Adding a `Clone` impl that does JS_DupValue makes sense.

> i thould i'd make a "utils" mod

All very welcome!

**Comment by theduke** [comment]
Regarding module loading: I already had an implementation somewhere, but I can't find the branch right now.

I'd prefer to have a pluggable module loading system with a trait like `ModuleLoader`. 
There can be a `FsModuleLoader` that loads from a directory, and `MemoryModuleLoader` that can load directly from eg a HashMap. 

That way modules can be bundled into a binary.

**Comment by andrieshiemstra** [comment]
about modules, i'm playing around with them to get a feel how quickjs actually implemented them, i'm also working on a "Native" module loader, e.g. loading modules like "native:utils" which is dynamically imported from rust functions. Once i have an idea about a complete interface i'll let you know.

about reflection (creating classes), in my project this is currently my number one source of valgrind errors, once i get a grip on them i'll et back to this

The fetch API is a bit more problematic than i originaly thought because it requires a lot of methods which return Promises, resolving them async required me to always use my lib in an EventQueue (to which i can add async jobs like resolving a Promise) do you have an idea about which way you want to go with stuff like that? it Also helped me do stuff like getting result async while using rust's async/await syntax.. which is cool..

**Comment by theduke** [comment]
> do you have an idea about which way you want to go with stuff like that?

`eval`  right now just naively runs execution until all promises are resolved.
But yeah, properly supporting async will require running an event loop and driving execution from there.

The [LocalPool](https://docs.rs/futures/0.3.13/futures/executor/struct.LocalPool.html) from futures might be a good choice.

**Comment by andrieshiemstra** [comment]
> The [LocalPool](https://docs.rs/futures/0.3.13/futures/executor/struct.LocalPool.html) from futures might be a good choice.

Ooh shiny, didn't know that one yet, i'll do some experimenting under https://github.com/HiRoFa/quickjs_es_runtime/issues/36
