### ISSUE TITLE
publishing libquickjs-sys with quickjs 2021-03-27 

### ISSUE THREAD

**Issue by andrieshiemstra** [theduke/quickjs-rs#116]
Hi, any chance of the updated libquickjs-sys being published any time soon? 

I'dd like to use the new JS_UpdateStackTop method

**Comment by andrieshiemstra** [comment]
@theduke any chance of this happening soon? if not i'd also like to know so i can plan alternatives

Kind regards

**Comment by theduke** [comment]
Sorry for the delay, working on it right now.

**Comment by theduke** [comment]
Published as `0.10.0`.

**Comment by andrieshiemstra** [comment]
Awesome, thanks!
