### ISSUE TITLE
Is the package maintained?

### ISSUE THREAD

**Issue by uwejan** [theduke/quickjs-rs#125]
Hey guys, i see no commits for a while, is this package abandoned?

**Comment by andrieshiemstra** [comment]
I think the biggest problem is quickjs itself not getting a lot of love. 

I actively maintain my own wrapper lib over here (https://github.com/HiRoFa/quickjs_es_runtime).

Kind regards

**Comment by uwejan** [comment]
@andrieshiemstra. To be honest, I am to consider an engine for my app.
Duktape seems to have a really good pulse. Many good projects already using it. But since it is C based and I use rust on my software, Hmmm. 
Any way I am on hunt searching the internet. I could not find a well maintained duktape package in rust, So I came accross here.

Thank you.

**Comment by andrieshiemstra** [comment]
if you want pure rust, consider boa (https://github.com/boa-dev/boa)

if you want higher compatibility and performance: roll your own deno (https://deno.com/blog/roll-your-own-javascript-runtime)

Kind regards

**Comment by uwejan** [comment]
> if you want pure rust, consider boa (https://github.com/boa-dev/boa)`
Boa as my google research says it is still slow in performance.
https://github.com/boa-dev/boa/issues/2203#issue-1316691115

> if you want higher compatibility and performance: roll your own deno (https://deno.com/blog/roll-your-own-javascript-runtime)
Can not use anything runs V8, I am looking for low footprint. Whereas V8 memory consumtion 28MB menimumm.

Thank you.

**Comment by andrieshiemstra** [comment]
In that case I think you'll like mine :) https://github.com/HiRoFa/quickjs_es_runtime

**Comment by theduke** [comment]
I haven't had much time to work on the bindings.

As mentioned, QuickJS is relatively abandoned. 
It's probably better to look for different options.
BUT:  QuickJS still absolutely trounces the other lightweight engines in ES compatibility.

I wouldn't say no to someone wanting to help out with maintenance!

**Comment by andrieshiemstra** [comment]
Hi, I'm happy to help with maintenance next time there's an update of quickjs but it's pretty much dead...

Every time I have some spare time I'm tempted to start a complete rewrite in rust but it seems quite the undertaking.. slimjs ofcourse is an awesome effort but it didn't make the code very readable or maintainable did it?

**Comment by andrieshiemstra** [comment]
Also noteworthy: https://github.com/second-state/wasmedge-quickjs

**Comment by uwejan** [comment]
Hey @andrieshiemstra 
I am back on this project, I wish to tkae your system design approach on this matter.
Say I have `myApp.exe` binary app, already compiled, built using C language, has Duktape integerated. I wanted to modify a `variable` value without re-compile here Duktape comes in handy,  ` ./script.js  db=abcd myApp.exe` Boom doen, no need to recompile.
So, my question for you, I to use rust-lang for my app and your lib, will I be able to do the same as mentioned?

**Comment by andrieshiemstra** [comment]
> Hey @andrieshiemstra I am back on this project, I wish to tkae your system design approach on this matter. Say I have `myApp.exe` binary app, already compiled, built using C language, has Duktape integerated. I wanted to modify a `variable` value without re-compile here Duktape comes in handy, ` ./script.js db=abcd myApp.exe` Boom doen, no need to recompile. So, my question for you, I to use rust-lang for my app and your lib, will I be able to do the same as mentioned?

Hi @uwejan 
Yes sure, you can run javascript and alter that script and run again without recompiling your executable
Please find my 'getting started' [here](https://github.com/andrieshiemstra/ScriptExtensionLayerExample) and feel free to ask questions here [here](https://github.com/HiRoFa/quickjs_es_runtime/discussions).

Kind regards
Andries Hiemstra
