### ISSUE TITLE
Proposal: change `JsValue::Int` to be `i64` instead of `i32`

### ISSUE THREAD

**Issue by a-rodin** [theduke/quickjs-rs#30]
Although not all 64-bit integers fit into JavaScript `Number` without lost of precision,  using`i32` instead of `i64` for integer types would be less restricting in my opinion.

See also #29.

**Comment by theduke** [comment]
QuickJS internally presents numbers either as `i32` or as `f64`.
Changing to `JsValue::Int(i64)` would produce some pretty confusing behaviour.
EG we would need to check the size and convert to float instead, which would produce floats when returned back to Rust. Unless we check if a float does not have a fraction and return it as `Int` but that could be not at all what you want. 
This would produce some awkward inconsistencies IMO.
What we could to though to make usage easier is to add conversion impls for `i64`.

**Comment by a-rodin** [comment]
> QuickJS internally presents numbers either as i32 or as f64.
I see. Actually, it is not standard (in a sense that users of JavaScript code shouldn't know about it), as JavaScript spec has only `Number` type which is 64-bit float.

**Comment by theduke** [comment]
Yeah I know, and maximum integers are `2^53 - 1`, but I guess they chose to represent things this way for performance.
That's why I opted for separate JsValue types instead of just number, but that of course introduces this awkwardness here.
I think `TryFrom/TryInto` impls for `u64`/`i64` is the best we can do.

**Comment by a-rodin** [comment]
Actually, the the 32-bit representation can be seen from JavaScript code when applying [bitwise operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Signed_32-bit_integers), so it makes sense that QuickJS uses 32-bit integers as one of the representations.

**Comment by a-rodin** [comment]
> I think TryFrom/TryInto impls for u64/i64 is the best we can do.
What do you think about `BigInt`? It has advantage of being a distinct type from `Number` in JavaScript.

**Comment by theduke** [comment]
I'm all for having it as a feature, but I don't think we can add automatic conversions from eg high `i64` to `BigInt` since they are not interchangable with regular numbers in code.
