### ISSUE TITLE
Free values returned by `JS_GetOwnPropertyNames` in `deserialize_object`

### ISSUE THREAD

**Issue by a-rodin** [theduke/quickjs-rs#36]
From [this thread in QuickJS mailing list](https://www.freelists.org/post/quickjs-devel/Iterate-over-JSValueObject,4) it looks like the properties returned by `JS_GetOwnPropertyNames` in `deserialize_object` should be freed using `JS_FreeAtom`.

**Comment by theduke** [comment]
Mhm, does this mean that you need to manually free the atom contained in [JSPropertyEnum](https://docs.rs/libquickjs-sys/0.3.0/libquickjs_sys/struct.JSPropertyEnum.html)?

**Comment by theduke** [comment]
PS: it's extremely frustrating that the code is completely undocumented.
Nothing contains comments on how to use them properly...

**Comment by a-rodin** [comment]
I think it means that `js_free_prop_enum` should be reimplemented in the Rust code.

See also https://www.freelists.org/post/quickjs-devel/Please-make-js-free-prop-enum-public,1.
