### ISSUE TITLE
Use #![deny(warnings)] and #![deny(missing_docs)] only for tests

### ISSUE THREAD

**Issue by a-rodin** [theduke/quickjs-rs#44]
Recently I questioned what would happen to projects dependent on this crate if a new Rust release starts to generate warnings for some parts of the crate's code (for example, like it started to show warnings for usage of `Box<Trait>` instead of `Box<dyn Trait>`). As far as I tested, this would prevent dependent projects from compiling. 

Maybe putting `#![deny(warnings)]` and `#![deny(missing_docs)]` in `lib.rs` behind `#[cfg(test)]` can make the crate more future-proof?

**Comment by theduke** [comment]
missing_docs wouldn't really make a difference. 

I'm fine with both though, also just for the sake of making development less annoying.
