### ISSUE TITLE
question: Requirement of RefUnwindSafe for Console and Callbacks

### ISSUE THREAD

**Issue by a-rodin** [theduke/quickjs-rs#50]
I'm curious why the requirement for `RefUnwindSafe` trait for `Console` and `Callback` traits is there. As I understand it, callbacks called by QuickJS might be interrupted, but it is still not clear to me how can it happen and is it possible to work around it.

I want to use [tracing](https://github.com/tokio-rs/tracing) to log data logged in JS code using `console.*` functions. However, in order to do it it seems to be necessary to pass application's [dispatcher](https://docs.rs/tracing/0.1.5/tracing/dispatcher/index.html) inside the closure, for example like this:

```rust
let mut dispatcher = std::sync::Arc::new(tracing::dispatcher::get_default(|d| d.clone()));                              
let mut builder = Context::builder().console(                                                                           
    move |level: quick_js::console::Level, args: Vec<JsValue>| {                                                        
        tracing::dispatcher::with_default(&mut *dispatcher, || {})                                                      
    },                                                                                                                  
);                                                                                                                      
```

However, requirement for `RefUnwindSafe` trait prevents doing it:

```
(dyn tracing::Subscriber + std::marker::Send + std::marker::Sync + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
```

Although It is possible to use for example `mpsc` channels to send log events from the console closure to the main thread, I want to ensure that there is no cleaner way to do it.

**Comment by theduke** [comment]
Sorry for the late response.

The console integration just uses callbacks under the hood. 

The callback handling captures panics and forwards them as errors. Since the callbacks are called from C code, we'd have UB problems otherwise.

https://doc.rust-lang.org/nightly/std/panic/fn.catch_unwind.html has a little bit more info.

You should be able to make things unwind safe by putting them in a Mutex.

**Comment by theduke** [comment]
Closing, feel free to inquire further.
