### ISSUE TITLE
Link failed as in #58

### ISSUE THREAD

**Issue by Mobilpadde** [theduke/quickjs-rs#60]
I'm getting the same issue as in #58 but cannot fix the same way, as I've included the this via `Cargo.toml`. Also, I'm quite new to rust :/

Anybody knows how to fix this?

I'm on `fedora 32`.

**Comment by theduke** [comment]
Thanks to @xu-cheng in #67  builds will now always use `-fPIC` which should fix this issue.

Will close once a new release is published.
