### ISSUE TITLE
Undefined and null are both JsValue::Null

### ISSUE THREAD

**Issue by pavlukivan** [theduke/quickjs-rs#81]
Before making a pull request that adds JsValue::Undefined I want to know the reasoning behind it not existing in the first place

**Comment by theduke** [comment]
I'm not sure why I did not add a `Undefined` variant, to be honest.

Maybe the C API did not offer a way to properly distinguish between them, or I just forgot. 

Happy to get a PR. That will be a breaking change, though.

**Comment by pavlukivan** [comment]
I'll do it along with a PR to add support for classes then I guess, to justify a version bump

**Comment by pavlukivan** [comment]
I decided to stop the work on classes support as I think my personal goals are way too different from this project's goals, I'll open a PR for adding undefined though
