### ISSUE TITLE
JS_DuplValue / JS_FreeValue support in quickjs_sys bindings?

### ISSUE THREAD

**Issue by andrieshiemstra** [theduke/quickjs-rs#82]
Hi,

i'm using your quickjs_sys crate for my own version of a wrapper lib (https://github.com/HiRoFa/quickjs_es_runtime) and was wondering why the JS_DupValue and JS_FreeValue from quickjs.h are not available, 

Upping and downing the refcount ourselves by casting and deciding when to free seems a bit hacky?

see https://github.com/HiRoFa/quickjs_es_runtime/blob/master/src/valueref.rs#L83 for my updated version of OwnedValueRef

the quickjs impl of JS_DupValue and JS_FreeValue pretty much seem to do exactly what i do with increment_ref_count and decrement_ref_count.

**Comment by theduke** [comment]
Those are `static inline` functions, which are not available to Rust code without extra work.

[This forum thread](https://users.rust-lang.org/t/ffi-and-static-functions-in-headers/9995) has some background and a workaround. 

Back then I found it easier to just duplicate them in Rust, though using the official code would be cleaner.

A PR using the method described in the link would definitely be welcome.

**Comment by theduke** [comment]
PS: I didn't have a lot of time for this repo, but I had planned to clean it up and extend the feature set this and next month, where I have some free time. 

I planned for module loading, async integration, timers/intervals, ...

I'd be happy to collaborate!

**Comment by andrieshiemstra** [comment]
Hi Thx, i will look into it.

I allready have module loading and a lot of async stuff working in my repo, i wanted to extend your work but i ended up changing so much it turned into a totaly different approach.

i'll let you know if i make any progress on the dup/free val methods.

Kind regards

**Comment by andrieshiemstra** [comment]
Thanks!
