### ISSUE TITLE
Upgrade to 2020-11-08

### ISSUE THREAD

**Issue by theduke** [theduke/quickjs-rs#89]
If anyone wants to help out: instructions are in https://github.com/theduke/quickjs-rs/blob/master/libquickjs-sys/README.md

**Comment by andrieshiemstra** [comment]
trying this out, the readme is slightly off the command is not
just quickjs-update
but
just update-quickjs

**Comment by andrieshiemstra** [comment]
ok, i updated under https://github.com/HiRoFa/quickjs-rs/tree/issue87

(yes i was 2 of, doesn't matter :)

running ```cargo test``` runs fine, 

but when running ```cargo test --all-features``` i get the following error

```
Applying patches...
Applying "js-tobigint64-overflow.patch"...
thread 'main' panicked at 'Could not apply patches: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libquickjs-sys/build.rs:142:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When examining that file the only file references i see are to libbf.c and quickjs.c which both still exist.. 

the only thing i can see is that the line number 11244 is now at 12201.. i tried changing that but lets face it, i have absolutely no clue what i'm doing here :) and it changed nothing...

so good luck to the next guy!

**Comment by theduke** [comment]
Haha, thanks. 

Please open a PR, I will look into fixing up the patch.

**Comment by andrieshiemstra** [comment]
reopended https://github.com/theduke/quickjs-rs/pull/90
