### ISSUE TITLE
Build failed on windows

### ISSUE THREAD

**Issue by expnn** [theduke/quickjs-rs#95]
Build failed on windows with toolchain `stable-x86_64-pc-windows-gnu`, msys2/MinGW64, and the following enviornments. 
```bash 
$ cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)
$ rustc --version 
rustc 1.46.0 (04488afe3 2020-08-24)
```

I found the issue comes from the following line from the `build.rs` file. 
https://github.com/theduke/quickjs-rs/blob/607bcce824a40b0cd3c664fec1e4b38aa1db1146/libquickjs-sys/build.rs#L145
The `fs::canonicalize` returns a path with a ['\\\\?\\'](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces) prefix (after unwrap), which will result in the calling of the `patch` command fail. See also [canonicalize doc](https://doc.rust-lang.org/std/fs/fn.canonicalize.html)

I temporily replaced the line to 
```rust 
.arg(patch.path())
```
to make it work. Any better ideas?

**Comment by theduke** [comment]
Ah yeah, the infamous Windows canonicalization issue...

I don't think we actually need to canonicalize the path, so your change should be fine.
