### ISSUE TITLE
Unable to accept arrays as callback params

### ISSUE THREAD

**Issue by kirjavascript** [theduke/quickjs-rs#99]
this works;

```rust
    context.add_callback("name", move |param: i32| {
        JsValue::Null
    }).unwrap();
```

this doesnt;

```rust
    context.add_callback("name", move |param: Vec<i32>| {
        JsValue::Null
    }).unwrap();
```

neither does;

```rust
    context.add_callback("name", move |param: &[i32]| {
        JsValue::Null
    }).unwrap();
```

and gives the error: `the trait Callback<_> is not implemented for [closure@src/bind.rs:98:34: 100:6]`

I see you can use `Arguments` to work around this, but it seems like Vec should work too

**Comment by theduke** [comment]
Yep, that was an oversight.
